### ISSUE TITLE
Error loading x 'x'

### ISSUE THREAD

**Issue by FlatEarthDave** [Desuuuu/klipper#79]
I had upgraded to the test version, with dgus, and it just had too many issues, so I reverted back to the master branch, flashed the screen and did make menuconfig. I got the error:

'Error loading kinematics 'corexy''

I deleted and unistalled everything, re-did everything, now I get:

'Error loading module 'motion''

tail of klipper log:

'=======================
Config error
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 157, in _connect
    self._read_config()
  File "/home/pi/klipper/klippy/klippy.py", line 143, in _read_config
    m.add_printer_objects(config)
  File "/home/pi/klipper/klippy/toolhead.py", line 600, in add_printer_objects
  File "/home/pi/klipper/klippy/toolhead.py", line 256, in __init__
    self.kin = mod.load_kinematics(self, config)
  File "/home/pi/klipper/klippy/kinematics/corexy.py", line 100, in load_kinematics
    return CoreXYKinematics(toolhead, config)
  File "/home/pi/klipper/klippy/kinematics/corexy.py", line 12, in __init__
    self.rails = [ stepper.PrinterRail(config.getsection('stepper_x')),
  File "/home/pi/klipper/klippy/stepper.py", line 269, in __init__
    elif default_position_endstop is None:
  File "/home/pi/klipper/klippy/stepper.py", line 339, in add_extra_stepper
    mcu_endstop.add_stepper(stepper)
  File "/home/pi/klipper/klippy/stepper.py", line 211, in PrinterStepper
    g1, g2 = [float(v.strip()) for v in gear.split(':')]
  File "/home/pi/klipper/klippy/klippy.py", line 120, in load_object
    raise self.config_error("Unable to load module '%s'" % (section,))
Error: Unable to load module 'motion_report'
webhooks client 3043645440: New connection
webhooks client 3043645440: Client info {'program': 'Moonraker', 'version': 'v0.7.1-60-gfdfab66'}'

Then I installed from the official repo, and it works now, except I get that stupid heater error.

**Comment by Desuuuu** [comment]
This doesn't appear to be related to this fork in any way. Please direct your issues where appropriate.
